apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dr-pool
  namespace: kafka-dr
  labels:
    strimzi.io/cluster: dr-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: true
  resources:
    requests:
      cpu: "200m"
      memory: 512Mi
    limits:
      cpu: "400m"
      memory: 768Mi
